export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './notifs.service';
import { NotifsService } from './notifs.service';
export * from './orderStatuses.service';
import { OrderStatusesService } from './orderStatuses.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './paymentMethods.service';
import { PaymentMethodsService } from './paymentMethods.service';
export * from './paymentStatuses.service';
import { PaymentStatusesService } from './paymentStatuses.service';
export * from './paymentTypes.service';
import { PaymentTypesService } from './paymentTypes.service';
export * from './pictures.service';
import { PicturesService } from './pictures.service';
export * from './productCategories.service';
import { ProductCategoriesService } from './productCategories.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './userProducts.service';
import { UserProductsService } from './userProducts.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AccountsService, CategoriesService, FilesService, JobsService, NotifsService, OrderStatusesService, OrdersService, PaymentMethodsService, PaymentStatusesService, PaymentTypesService, PicturesService, ProductCategoriesService, ProductsService, RolesService, UserProductsService, UsersService];
