/**
 * FOS ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageBlocTemplate } from './pageBlocTemplate';
import { BlocTemplateBackup } from './blocTemplateBackup';


export interface BlocTemplate { 
    id?: number;
    name?: string | null;
    langue?: string | null;
    type?: string | null;
    tableName?: string | null;
    itemCount?: number;
    active?: boolean;
    imageUrl?: string | null;
    metadata?: string | null;
    pageBlocTemplates?: Array<PageBlocTemplate> | null;
    blocTemplateBackups?: Array<BlocTemplateBackup> | null;
}

