/**
 * FOS ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Center } from './center';
import { MyEvent } from './myEvent';
import { Region } from './region';


export interface City { 
    id?: number;
    name?: string | null;
    regionId?: number;
    region?: Region;
    myEvents?: Array<MyEvent> | null;
    centers?: Array<Center> | null;
}

