/**
 * FOS ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetailEligibility } from './detailEligibility';


export interface Eligibility { 
    name?: string | null;
    list?: Array<DetailEligibility> | null;
    note?: number;
}

