/**
 * packaging ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Notif { 
    id?: number;
    creationDate?: string;
    userReceiverId?: number;
    userReceiver?: User;
    isReceiverAdmin?: boolean;
    userSenderId?: number;
    userSender?: User;
    isSenderAdmin?: boolean;
    status?: string | null;
    ackDate?: string | null;
    message?: string | null;
    type?: string | null;
    title?: string | null;
    link?: string | null;
}

