/**
 * packaging ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Product } from './product';


export interface ProductCategory { 
    productId?: number;
    product?: Product;
    categoryId?: number;
    category?: Category;
}

