/**
 * packaging ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductCategory } from './productCategory';


export interface ProductCategoryGetAllDto { 
    list?: Array<ProductCategory> | null;
    count?: number;
}

